[package]
name = "nextshell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
workflow-types = { path = "../workflow-types" }
nextshell-workflows-types = { path = "../workflows/workflow-types" }
